In [1]:
import pandas as pd
import seaborn as sns

# titanic  데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
df = titanic.loc[0:9, ['age', 'fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [2]:
# 조건식 적용(20세 미만: age < 20)
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [3]:
# 불린 인덱싱(20세 미만의 조건을 충족하는 행을 필터링)
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [6]:
# 불린 인덱싱(20세 미만의 조건을 충족하는 행을 필터링)
df.loc[df['age'] < 20]['age']

7     2.0
9    14.0
Name: age, dtype: float64

In [7]:
df.loc[df['age'] < 20, 'age']

7     2.0
9    14.0
Name: age, dtype: float64

In [3]:
df.loc[~(df['age'] < 20)]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [5]:
# 나이가 10대(10~19세)인 승객(AND 논리연산)
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [18]:
mask2 = (titanic.age < 10) & (titanic.sex =='female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [19]:
# 나이가 10세 미만(0~9세) 또는 60세 이상인 승객 (OR  논리연산)
# age, sex, alone 열만 선택 (loc 인덱서, fancy indexing)
mask3 = (titanic.age < 10) | (titanic.age >=60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
print(df_under10_morethan60.head())

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [20]:
import pandas as pd
import seaborn as sns

In [21]:
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
print(df.tail())
print(type(df))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75
<class 'pandas.DataFrame'>

In [22]:
addition = df + 10
print(addition.tail())

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [23]:
df = titanic.loc[0:9, ['age', 'fare']]
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [24]:
# 20세 미만의 조건을 충족하는 행을 필터링
df.query('age < 20')

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [25]:
# 나이가 20세 이상이고 요금이 15미만인 조건을 모두 충족하는 행을 필터링
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

### 불린 마스크
조건식의 결과로 만들어지는 True/False값의 집합

### 불린 인덱싱
불린 마스크를 이용해서 True인 데이터만 선택하는 것
예) titanic[mask] => True인 행만 선택

In [26]:
df_boolean = titanic[mask1 | mask2]
df_boolean

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [28]:
mask1 = titanic['embark_town'] =='Southampton'
mask2 = titanic['embark_town'].str.match('Queenstown')
df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# str타입이랑 string타입이랑 다른거임? 지피티한테 물어봐
import pandas as pd

fruit_names = pd.Series(['Apple', 'Banana', 'Cherry'])
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [30]:
import pandas as pd

fruit_names = pd.Series(['Apple', 'Banana', 'Cherry'], dtype='string')
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: string

In [31]:
import pandas as pd

fruit_names = pd.Series(['Apple', 'Banana', 'Cherry'], dtype=pd.StringDtype)
fruit_names

C:\Users\KDT59\AppData\Local\Temp\ipykernel_24172\7099573.py:3: UserWarning: Instantiating StringDtype without any arguments.Pass a StringDtype instance to silence this warning.
  fruit_names = pd.Series(['Apple', 'Banana', 'Cherry'], dtype=pd.StringDtype)

0     Apple
1    Banana
2    Cherry
dtype: string

In [32]:
fruit_names.astype('string')
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: string

# 문자열 메서드 사용하기

In [33]:
import pandas as pd
import numpy as np

In [35]:
# 텍스트로 이루어진 시리즈 배열 만들기(자료형 지정, 일반 객체 Object 생성)
ser = pd.Series(['Apple_사과', 'Banana_바나나', 'Cherry_체리', np.nan],
                index=['First', 'Second', 'Third', 'Fourth'])
print(ser)

First       Apple_사과
Second    Banana_바나나
Third      Cherry_체리
Fourth           NaN
dtype: str

In [51]:
# 텍스트로 이루어진 시리즈 배열 만들기(자료형 지정, 일반 객체 Object 생성)
ser = pd.Series(['Apple_사과', 'Banana_바나나', 'Cherry_체리', np.nan],
                index=['First', ' Second', 'Third ', 'Fourth '], dtype='string')
print(ser)

First        Apple_사과
 Second    Banana_바나나
Third       Cherry_체리
Fourth           <NA>
dtype: string

In [52]:
print(ser.str.lower())
print(ser)

First        apple_사과
 Second    banana_바나나
Third       cherry_체리
Fourth           <NA>
dtype: string
First        Apple_사과
 Second    Banana_바나나
Third       Cherry_체리
Fourth           <NA>
dtype: string

In [53]:
print(ser.str.len())

First         8
 Second      10
Third         9
Fourth     <NA>
dtype: Int64

In [54]:
# 문자열 분할
print(ser.str.split('_'))
print()

# 문자열을 분할하여 DataFrame으로 확장
print(ser.str.split('_', expand=True))
print()

# 분할된 문자열 중 특정 요소 선택
print(ser.str.split('_').str.get(1))

First        [Apple, 사과]
 Second    [Banana, 바나나]
Third       [Cherry, 체리]
Fourth              <NA>
dtype: object

              0     1
First     Apple    사과
 Second  Banana   바나나
Third    Cherry    체리
Fourth     <NA>  <NA>

First        사과
 Second     바나나
Third        체리
Fourth     <NA>
dtype: object

In [55]:
print(ser.str.split('_').str.get(0))

First       Apple
 Second    Banana
Third      Cherry
Fourth       <NA>
dtype: object

In [56]:
# 행 인덱스 추출
print(ser)

First        Apple_사과
 Second    Banana_바나나
Third       Cherry_체리
Fourth           <NA>
dtype: string

In [57]:
idx = ser.index
print(idx)

Index(['First', ' Second', 'Third ', 'Fourth '], dtype='str')

In [58]:
# 양쪽 공백 제거한다
idx.str.strip()

Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [59]:
idx.str.rstrip()

Index(['First', ' Second', 'Third', 'Fourth'], dtype='str')

In [60]:
idx.str.lstrip()

Index(['First', 'Second', 'Third ', 'Fourth '], dtype='str')

In [ ]:
# 정규식 표현 찾아서 정리해라.

In [61]:
print(ser.str.replace("_", ":", regex=False))

First        Apple:사과
 Second    Banana:바나나
Third       Cherry:체리
Fourth           <NA>
dtype: string

In [64]:
# replace()는 문자열 교체
# regex = False 일반 문자 그대로 찾아라
# regex = True 정규식 표현으로 찾아라
# 영어 소문자, 대문자, 공백을 제외한 문자를 제거한다.
print(ser.str.replace("[a-zA-Z\s_]", "", regex=True))

First        사과
 Second     바나나
Third        체리
Fourth     <NA>
dtype: string

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\KDT59\AppData\Local\Temp\ipykernel_24172\3321622661.py:5: SyntaxWarning: invalid escape sequence '\s'
  print(ser.str.replace("[a-zA-Z\s_]", "", regex=True))

In [69]:
# r은 raw 임 왜 이걸쓰냐면 regex상황에 바로 넣어야함
# escape문이 들어가는 경우 이슈가 발생할수 있음. 그래서 그냥 문자열 그대로 정규식에 넣기위해 r을 활용해서 작성함.
# 첫글자가 A또는 B로 시작하고 그 뒤에 소문자가 하나이상 있는 문자열 검색
# 그리고 정규표현식은 후위표기법으로 작성해야함.

print(ser.str.replace(r"[^가-힣]", "", regex=True))

First        사과
 Second     바나나
Third        체리
Fourth     <NA>
dtype: string

In [70]:
print(ser.str.contains(r"[A|B][a-z]+"))

First       True
 Second     True
Third      False
Fourth      <NA>
dtype: boolean

In [75]:
# fullmatch() 전체 문자열의 패턴 일치 여부 확인
# contains()는 문자열이 포함되어있으면 True
# fullmatch()는 전체가 정확하게 같으면 True
# 첫글자가 A 또는 B로 시작하고, 그 뒤에 소문자가 하나이상인 경우 True
print(ser.str.fullmatch(r"[AB][a-z]+"))

First      False
 Second    False
Third      False
Fourth      <NA>
dtype: boolean