# 시리즈와 데이터 프레임의 차이
- 시리즈는 딕셔너리 한계를 세로로 펼친 것. 키가 인덱스가 됨
- 데이터프레임은 여러개의 리스트를 표로 만든 것, 키가 열이 됨

In [79]:
import pandas as pd

exam_data = {'이름': '이선희', 
             '수학': 80, 
             '영어': 100, 
             '국어': 90
             }

print(exam_data)
exam_data = pd.Series(exam_data)


print(exam_data)

{'이름': '이선희', '수학': 80, '영어': 100, '국어': 90}
이름    이선희
수학     80
영어    100
국어     90
dtype: object

In [80]:
exam_data = pd.DataFrame(exam_data)
print(exam_data)
print(type(exam_data))

      0
이름  이선희
수학   80
영어  100
국어   90
<class 'pandas.DataFrame'>

In [81]:
import pandas as pd

exam_data2 = {'이름': ['이선희','홍길동', '춘향좌'], 
             '수학': [80, 86, 43], 
             '영어': [100, 32, 23], 
             '국어': [90, 34, 23]
             }

print(exam_data2)

{'이름': ['이선희', '홍길동', '춘향좌'], '수학': [80, 86, 43], '영어': [100, 32, 23], '국어': [90, 34, 23]}

In [82]:
exam_data = {'이름': '이선희', 
             '수학': 80, 
             '영어': 100, 
             '국어': 90
             }

exam_data = pd.Series(exam_data) # 시리즈로 변환안하고 바로 딕셔너리로 변환하면 에러뜸 
df  = pd.DataFrame(exam_data)
print(df)

      0
이름  이선희
수학   80
영어  100
국어   90

In [83]:
exam_data2 = {'이름': ['이선희','홍길동', '춘향좌'], 
             '수학': [80, 86, 43], 
             '영어': [100, 32, 23], 
             '국어': [90, 34, 23]
             }

df = pd.DataFrame(exam_data2)
df = df.set_index('이름')
df

     수학   영어  국어
이름
이선희  80  100  90
홍길동  86   32  34
춘향좌  43   23  23

In [84]:
print(df['수학'])

이름
이선희    80
홍길동    86
춘향좌    43
Name: 수학, dtype: int64

In [85]:
print(df['영어'])

이름
이선희    100
홍길동     32
춘향좌     23
Name: 영어, dtype: int64

In [86]:
df.loc['홍길동']

수학    86
영어    32
국어    34
Name: 홍길동, dtype: int64

In [87]:
print(df.loc['홍길동', '국어'])

34

In [88]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름': ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)

# '이름' 열을 새로운 인덱스로 지정하고, df 객체에 변경 사항 반영
df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [89]:
# 데이터 프레임 df의 특정 원소 2개 이상 선택('서준'의 음악, 체육점수)
c = df.loc['서준', ['음악', '체육']]
print(c)
d = df.iloc[0,[2, 3]]
print(d)
e = df.loc['서준', '음악': '체육']

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [90]:
a = df.loc['서준', '음악']
print(a)
b = df.iloc[0, 2]
print(b)

85
85

In [91]:
exam_data = {'이름': ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [92]:
df = df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [93]:
df.iloc[0, 3] = 80
print(df.iloc[0, 3])

80

In [94]:
# 여러 개의 원소값을 수정하는 방법
df.loc['서준', ['음악', '체육']] = 90
print(df)

    수학  영어   음악  체육
이름
서준  90  98   90  90
우현  80  89   95  90
인아  70  95  100  90

In [95]:
df.loc['서준', ['음악', '체육']] = 90, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   90  50
우현  80  89   95  90
인아  70  95  100  90

In [96]:
df.loc[['서준', '우현'],['음악', '체육']] = 90, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   90  50
우현  80  89   90  50
인아  70  95  100  90

In [97]:
df.loc[['서준', '우현'], ['음악', '체육']] = [[90, 80], [60, 50]]
print(df)

    수학  영어   음악  체육
이름
서준  90  98   90  80
우현  80  89   60  50
인아  70  95  100  90

In [98]:
# 데이터 프레임의 행과 열을 서로 바꾸는 방법
# DataFrame() 함수로 데이터 플임 변환, 변수 df에 저장
exam_data = {'이름': ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [99]:
df = df.transpose()
print(df)

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [100]:
print(df.transpose())

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [101]:
print(df.T)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [102]:
exam_data = {'이름': ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [103]:
ndf = df.set_index(['이름'])
print(ndf)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [104]:
ndf = df.set_index('음악')
print(ndf)

     이름  수학  영어   체육
음악
85   서준  90  98  100
95   우현  80  89   90
100  인아  70  95   90

In [105]:
ndf = df.set_index(['수학', '영어'])
print(ndf)

       이름   음악   체육
수학 영어
90 98  서준   85  100
80 89  우현   95   90
70 95  인아  100   90

In [106]:
# 정수형 위치 인덱스로 초기화
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

In [107]:
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value=0)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14
r3   0   0   0   0   0
r4   0   0   0   0   0

In [123]:
# 딕셔너리를 정의 
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])

In [ ]:
# index를 새로만들고 기존의 index를 변수로 갖고오기
ndf = df.reset_index()
print(ndf)

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [119]:
# index를 새로만들고 기존의 index를 변수로 갖고오기
ndf1 = ndf.reset_index()
print(ndf1)

   level_0 index  c0  c1  c2  c3  c4
0        0    r0   1   4   7  10  13
1        1    r1   2   5   8  11  14
2        2    r2   3   6   9  12  15

In [120]:
# index를 새로만들고 기존의 index를 변수로 갖고오기
ndf1 = ndf1.reset_index()
print(ndf1)

ValueError: cannot insert level_0, already exists

In [124]:
print(df)
df = df.reset_index(drop=True)
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [125]:
ndf = df.sort_index(ascending=False)
print(ndf)

   c0  c1  c2  c3  c4
2   3   6   9  12  15
1   2   5   8  11  14
0   1   4   7  10  13

In [127]:
ndf = ndf.sort_values('c3', ascending=True)
ndf

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [128]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': 100, '영어': 80, '수학': 90})
student2 = pd.Series({'수학': 80, '국어': 90, '영어': 80})

print(student1)
print()
print(student2)

# 두학생의 과목별 점수로 사칙연산 수행
addition = student1 + student2
print(type(addition))

print(addition)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64
<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [129]:
subtraction = student1 - student2
print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [130]:
multiplication = student1 * student2
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [131]:
division = student1 / student2
print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [132]:
# 사칙연산 결과를 데이터 프레임으로 합치기(시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [133]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': np.nan, '영어': 80, '수학': 90})
student2 = pd.Series({'수학': 80, '국어': 90})

print(student1)
print(student2)

addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2
print(type(division))
print()

# 사칙연산 결과를 데이터프레임으로 합치기(시리즈 -> 데이터 프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
<class 'pandas.Series'>

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [ ]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': np.nan, '영어': 80, '수학': 90})
student2 = pd.Series({'수학': 80, '국어': 90})

print(student1)
print(student2)

# 두 학생의 과목별 점수로 사칙연산 수행(연산 메서드 사용)
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

In [2]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
print(df.head())
print()
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

<class 'pandas.DataFrame'>

In [4]:
addition = df + 10
print(addition.head())
print()
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

<class 'pandas.DataFrame'>

In [5]:
import pandas as pd
import seaborn as sns 

# titanic 데이터셋에서 age, fare 2개 열ㅇ르 선택하여 데이터 프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
print(df.tail())
print()
print(type(df))
print()

# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.tail())
print()
print(type(addition))
print()

# 데이터프레임끼리 연산하기(addition - df)
subtraction = addition - df
print(subtraction.tail())
print()
print(type(subtraction))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

<class 'pandas.DataFrame'>

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

<class 'pandas.DataFrame'>

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

<class 'pandas.DataFrame'>

In [6]:
# 사칙연산 수행(연산 메서드 사용)
sample1 = addition.tail()
sample2 = addition.tail().fillna(0.0)

print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age   fare
886  37.0  23.00
887  29.0  40.00
888   0.0  33.45
889  36.0  40.00
890  42.0  17.75

In [15]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)