In [3]:
import pandas as pd

# 행 인덱스/열 이름 짖ㅇ하여, 데이터프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                  index=['준서', '예은'],
                  columns=['나이', '성별', '학교'])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [4]:
print(df.index)

Index(['준서', '예은'], dtype='str')

In [5]:
print(df.columns)

Index(['나이', '성별', '학교'], dtype='str')

# index와 columns를 건드려서 원하는 인덱스와 변수명으로 바꿔보자

In [ ]:
# 방법 1
df.index = ['학생1', '학생2']
df.columns = ['연령', '남녀', '소속']

print(df)
print('\n')
print(df.index)
print('\n')
print(df.columns)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중


Index(['학생1', '학생2'], dtype='str')


Index(['연령', '남녀', '소속'], dtype='str')

In [11]:
# 방법 2 rename
import pandas

# 행 인덱스/열 이름 지정하여 데이터 프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                  index=['준서', '예은'],
                  columns =['나이', '성별', '학교'])

print(df)

df_rename = df.rename(columns={'나이': '연령', '성별':'남녀', '학교': '소속'})

print(df_rename)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [12]:
df = df.rename(index={'준서': '학생1', '예은': '학생2'})
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

# 행렬 삭제

In [ ]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'수학': [90, 80, 70], '영어': [98, 89, 95],
             '음악': [85, 95, 100], '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

df2 = df.copy()
df2 = df2.drop('우현')
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [14]:
df3 = df.copy()
df3 = df3.drop(['우현', '인아'], axis=0)
print(df3)

    수학  영어  음악   체육
서준  90  98  85  100

In [15]:
# 행 삭제
df4 = df.copy()
df4 = df.drop(['우현', '인아'], axis='index')
print(df4)

    수학  영어  음악   체육
서준  90  98  85  100

In [16]:
df5 = df.copy()
df5 = df.drop(index=['우현'])
print(df5)

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [17]:
# 열 삭제
import pandas as pd

exam_data = {'수학': [90, 80, 70], '영어': [98, 89, 95],
             '음악': [85, 95, 100], '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [19]:
df3 = df.copy()
df3 = df3.drop(['영어', '음악'], axis=1)
print(df3)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [21]:
df4 = df.copy()
df4 = df4.drop(['영어', '음악'], axis='columns')
print(df3)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [23]:
df5 = df.copy()
df5 = df5.drop(columns=['수학'])
print(df5)
print(type(df5))

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90
<class 'pandas.DataFrame'>

## 데이터 프레임의 행 데이터를 선택하기 위해서는 loc과 iloc 인덱서를 사용한다. 인덱스 이름을 기준으로 행을 선택할 때는 loc을 이용하고, 정수 위치 인덱스를 사용할때는 iloc을 이용한다.

In [24]:
label1 = df.loc['서준']
position1 = df.iloc[0]
print(label1)
print()
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [25]:
# 데이터 프레임에서 여러 행 선택
label2 = df.loc[['서준', '우현']]
position2 = df.iloc[[0, 1]]
print(label2)
print()
print(position2)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [28]:
# 열조회
print(df.loc[:, '수학'])
print(df.iloc[:, 0])

서준    90
우현    80
인아    70
Name: 수학, dtype: int64
서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [29]:
math1 = df['수학']
print(math1)
print()
print(type(math1))

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

<class 'pandas.Series'>

In [30]:
music_gym = df[['음악', '체육']]
print(music_gym)
print()
print(type(music_gym))

     음악   체육
서준   85  100
우현   95   90
인아  100   90

<class 'pandas.DataFrame'>

In [32]:
math2 = df[['수학']]
print(math2)
print()
print(type(math2))

    수학
서준  90
우현  80
인아  70

<class 'pandas.DataFrame'>

In [33]:
df.iloc[::2]

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [34]:
df.iloc[0:3:2]

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [36]:
df.iloc[::-1]

    수학  영어   음악   체육
인아  70  95  100   90
우현  80  89   95   90
서준  90  98   85  100

In [37]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름': ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)

# '이름' 열을 새로운 인덱스로 지정하고, df 객체에 변경 사항 반영
df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [38]:
a = df.loc['서준', '음악']
print(a)
b = df.iloc[0, 2]
print(b)

85
85

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [41]:
print(e)
f = df.iloc[0, 2:]
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [42]:
# df 2개 이상의 행과 열에 속하는 원소들 선택('서준', '우현'의 '음악', '체육' 점수)
g = df.loc[['서준', '우현'], ['음악', '체육']]
print(g)

h = df.iloc[[0, 1], [2, 3]]
print(h)

i = df.loc['서준':'우현', '음악':'체육']
print(i)


j = df.iloc[0:2, 2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [45]:
# df 2개 이상의 행과 열에 속하는 원소들 선택('서준', '우현'의 '음악', '체육' 점수)
g = df.loc[['서준', '우현'],['음악', '체육']]
print(g)
h = df.iloc[[0, 1], [2, 3]]
print(h)
i = df.loc['서준':'우현', '음악': '체육']
print(i)
j = df.iloc[0:2, 2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [46]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

df['국어'] = 80
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [ ]:
df['미술'] = [80, 90, 100]
print(df)

In [ ]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)
print()

# 새로운 row 추가 -같은 원소 값 입력
df.loc[3] = 0
print(df)

# 새로운 행 추가 - 원소 값 여러개의 배열 입력
df.loc[4] = ['동규', 90, 80, 70, 60]
print(df)

# 새로운 행 추가 - 기존행 복사
df.loc['행5'] = df.loc[3]
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60
    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [ ]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)


df = df.set_index('이름')
print(df)

# 데이터 프레임 df의 특정 원소를 변경하는 방법: '서준'의 '체육' 점수
df.iloc[0][3] = 80
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

C:\Users\KDT59\AppData\Local\Temp\ipykernel_4152\288641835.py:17: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.iloc[0][3] = 80
C:\Users\KDT59\AppData\Local\Temp\ipykernel_4152\288641835.py:20: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc['서준']['체육'] = 90

In [ ]:
df.loc['서준']['체육'] = 90
print(df)

df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

C:\Users\KDT59\AppData\Local\Temp\ipykernel_4152\3794724790.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc['서준']['체육'] = 90

In [52]:
df.loc['서준']['체육'] = 100
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

C:\Users\KDT59\AppData\Local\Temp\ipykernel_4152\1038348093.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc['서준']['체육'] = 100

In [56]:
df.loc['서준','체육'] = 120
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  120
우현  80  89   95   90
인아  70  95  100   90

In [60]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)


df = df.set_index('이름')
print(df)

df.loc[3] = 0
print(df)

df.loc[4] = ['동규', 90, 80, 70]
print(df)

# 새로운 행 추가 - 기존 행 복사
df.loc['행5'] = df.loc[3]
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
3    0   0    0    0
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
3    0   0    0    0
4   동규  90   80   70
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
3    0   0    0    0
4   동규  90   80   70
행5   0   0    0    0

In [ ]:
df.loc['서준', ['음악', '체육']] = 50
print(df)

df.loc['서준', ['음악', '체육']] = 100, 50
print(df)

In [61]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)


df = df.set_index('이름')
print(df)

df = df.transpose()
print(df)

df = df.T
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [4]:
print(df['수학'])
print(df.수학)

0    90
1    80
2    70
Name: 수학, dtype: int64
0    90
1    80
2    70
Name: 수학, dtype: int64

In [9]:
df.loc[0, ['음악', '체육']]

음악     85
체육    100
Name: 0, dtype: int64

In [13]:
df['국어'] = [90,80,70]
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  90
1  우현  80  89   95   90  80
2  인아  70  95  100   90  70

In [14]:
df['체육'] =100 
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  90
1  우현  80  89   95  100  80
2  인아  70  95  100  100  70

In [ ]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)

In [17]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  90
1  우현  80  89   95  100  80
2  인아  70  95  100  100  70
3   0   0   0    0    0   0

In [18]:
df.loc[4] = ['정선', 34, 43, 32, 54, 23]
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  90
1  우현  80  89   95  100  80
2  인아  70  95  100  100  70
3   0   0   0    0    0   0
4  정선  34  43   32   54  23

In [20]:
# 기존의 행을 복사해서 새로운 행을 만드는 방법
df.loc['행5'] = df.loc[2]
df

    이름  수학  영어   음악   체육  국어
0   서준  90  98   85  100  90
1   우현  80  89   95  100  80
2   인아  70  95  100  100  70
3    0   0   0    0    0   0
4   정선  34  43   32   54  23
행5  인아  70  95  100  100  70

In [21]:
df.loc['행6'] = df.loc['행5']
df

    이름  수학  영어   음악   체육  국어
0   서준  90  98   85  100  90
1   우현  80  89   95  100  80
2   인아  70  95  100  100  70
3    0   0   0    0    0   0
4   정선  34  43   32   54  23
행5  인아  70  95  100  100  70
행6  인아  70  95  100  100  70

(3, 2)

In [62]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

# 특정 열(column)을 데이터프레임의 행 인덱스로 설정
ndf = df.set_index(['이름'])
print(ndf)

ndf2 = ndf.set_index('음악')
print(ndf2)

ndf3 = ndf.set_index(['수학', '음악'])
print(ndf3)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90
        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [65]:
# df3 = df.copy()
# df3 = df3.drop(columns=['수학'], axis=1)
# print(df3)

In [2]:
import pandas as pd

# DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장
exam_data = {'이름' : ['서준', '우현', '인아'],
             '수학': [90, 80, 70],
             '영어': [98, 89, 95],
             '음악': [85, 95, 100],
             '체육': [100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)

print(type(df['수학']))
print(type(df.수학))

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
<class 'pandas.Series'>
<class 'pandas.Series'>