In [2]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [5]:
df = titanic.loc[0:9, ['age', 'fare']]
df
# 불린 시리즈를 새로운 열로 추가
df['age_under_20'] = df['age'] < 20
df.head()

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False

In [6]:
# query 메서드 활용
import pandas as pd
import seaborn as sns

# titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
df = titanic.loc[0:9, ['age', 'fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [7]:
# 20세 미만의 조건을 충족하는 행을 필터링
df.query('age < 20')

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [ ]:
# 나이가 20세 이상이고 요금이 15 미만인 조건을 모두 충족하는 행을 필터링
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

In [9]:
# 라이브러리 불러오기
import seaborn as sns
import pandas as pd

# titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 디스플레이 설정 변경 - 출력할 최대 열의 개수
pd.set_option('display.max_columns', 10)

# 탑승한 도시가 "Southampton", "Queenstown"인 승객만 따로 추출 - 불린 인덱싱
mask1 = titanic['embark_town'] == 'Southampton'
mask2 = titanic['embark_town'] == 'Queenstown'
df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [10]:
# isin() 필터링: isin 안에 들어있는 집합안에 있는 값이 있는경우만 추출
isin_filter = titanic['embark_town'].isin(["Southampton", "Queenstown"])
df_isin = titanic[isin_filter]
df_isin.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [11]:
import pandas as pd

# 텍스트로 이루어진 시리즈 배열 만들기(자료형 미지정)
fruit_name = pd.Series(['Apple', 'Banana', 'Cherry'])

# 시리즈 출력
fruit_name

0     Apple
1    Banana
2    Cherry
dtype: str

In [12]:
# 자료형 지정: 'string' 사용
pd.Series(['Apple', 'Banana', 'Cherry'], dtype='string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [14]:
# 자료형 지정: pd.StringDtype() 사용
pd.Series(['Apple', 'Banana', 'Cherry'], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [17]:
# 자료형 변환
print(fruit_name)
fruit_name.astype('string')

0     Apple
1    Banana
2    Cherry
dtype: str

0     Apple
1    Banana
2    Cherry
dtype: string

In [18]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 텍스트로 이루어진 시리즈 배열 만들기(자료형 미지정)
ser = pd.Series(['Apple_사과', 'Banana_바나나', 'Cherry_체리', np.nan],
                index=['First', 'Second', 'Third', 'Fourth'])

print(ser)
print()


# 텍스트로 이루어진 시리즈 배열 만들기(string 자료형 지정)
ser2 = pd.Series(['Apple_사과', 'Banana_바나나', 'Cherry_체리', np.nan],
                index=['First', 'Second', 'Third', 'Fourth'], dtype='string')

print(ser2)

First       Apple_사과
Second    Banana_바나나
Third      Cherry_체리
Fourth           NaN
dtype: str

First       Apple_사과
Second    Banana_바나나
Third      Cherry_체리
Fourth          <NA>
dtype: string

In [19]:
# 소문자로 변환
print(ser.str.lower())
print()

# 대문자로 변환
print(ser.str.upper())
print()

# 문자열 길이 계산
print(ser.str.len())

First       apple_사과
Second    banana_바나나
Third      cherry_체리
Fourth           NaN
dtype: str

First       APPLE_사과
Second    BANANA_바나나
Third      CHERRY_체리
Fourth           NaN
dtype: str

First      8.0
Second    10.0
Third      9.0
Fourth     NaN
dtype: float64

In [20]:
# 문자열 분할
print(ser.str.split("_"))
print()

# 문자열을 분할하여 DataFrame으로 확장
print(ser.str.split('_', expand=True))
print()

# 분할된 문자열 중 특정 요소 선택
print(ser.str.split('_').str.get(1))

First       [Apple, 사과]
Second    [Banana, 바나나]
Third      [Cherry, 체리]
Fourth              NaN
dtype: object

             0    1
First    Apple   사과
Second  Banana  바나나
Third   Cherry   체리
Fourth     NaN  NaN

First      사과
Second    바나나
Third      체리
Fourth    NaN
dtype: object

In [21]:
# 행 인덱스를 추출
idx = ser.index
print(idx)

# 양쪽 공백 제거
print(idx.str.strip())

# 왼쪽 공백 제거
print(idx.str.lstrip())

# 오른쪽 공백 제거
print(idx.str.rstrip())

Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [22]:
# 문자열 교체("_"를 찾아서 ":"으로 변경)
print(ser.str.replace("_", ":", regex=False))
print()

# 정규 표현식을 사용한 문자열 교체(영문 알파벳이 아닌 문자 제거)
print(ser.str.replace("[^a-zA-Z\s]", '', regex=True))

First       Apple:사과
Second    Banana:바나나
Third      Cherry:체리
Fourth           NaN
dtype: str

First      Apple
Second    Banana
Third     Cherry
Fourth       NaN
dtype: str

<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:6: SyntaxWarning: invalid escape sequence '\s'
C:\Users\USER\AppData\Local\Temp\ipykernel_14708\2624469517.py:6: SyntaxWarning: invalid escape sequence '\s'
  print(ser.str.replace("[^a-zA-Z\s]", '', regex=True))

In [23]:
# 인덱싱 - 각 문자열의 첫 번째 문자 선택
print(ser.str[0])
print()

# 슬라이싱 - 각 문자열의 첫 번째부터 세 번째 문자 선택
print(ser.str[0:4])

First       A
Second      B
Third       C
Fourth    NaN
dtype: str

First     Appl
Second    Bana
Third     Cher
Fourth     NaN
dtype: str

In [ ]:
# 특정 문자 포함 여부 확인, NA 값을 False로 처리
contains_A = ser.str.contains("A", na=False)
print(contains_A)
print()

# 패턴 포함 여부 확인
contains_pattern = ser.str.contains(r"[A|B][a-z]+")
print(contains_pattern)
print()

# 전체 문자열의 패턴 일치 여부 확인
fullmatch_pattern = ser.str.fullmatch(r"[A|B][a-z]+")
print(contains_pattern)
print()

# 전체 문자열의 패턴 일치 여부 확인
fullmatch_pattern = ser.str.fullmatch(r"[A|B][a-z]+")
print(fullmatch_pattern)

First      True
Second    False
Third     False
Fourth    False
dtype: bool

In [25]:
# 새로운 시리즈 생성
ser3 = pd.Series(["a1", "b2", "c3", "d4a5", "e6e7", "f8"], dtype='string')

# 숫자만 추출
digits = ser3.str.extractall(r"(\d)").groupby(level=0).agg(''.join)
print(digits)
print()


# 알파벳만 추출
letters = ser3.str.extractall(r"([a-z])").groupby(level=0).agg(''.join)
print(letters)
print()

# 숫자를 별도의 컬럼으로 분리
split_columns = ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

    0
0   1
1   2
2   3
3  45
4  67
5   8

    0
0   a
1   b
2   c
3  da
4  ee
5   f