In [1]:
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [2]:
ndf = df.reset_index()
print(ndf)

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [19]:
ndf = ndf.rename(columns={'index': 'r_series'})
print(ndf)

  r_series  c0  c1  c2  c3  c4
0       r0   1   4   7  10  13
1       r1   2   5   8  11  14
2       r2   3   6   9  12  15

In [22]:
ndf.set_index('r_series')
ndf

  r_series  c0  c1  c2  c3  c4
0       r0   1   4   7  10  13
1       r1   2   5   8  11  14
2       r2   3   6   9  12  15

In [24]:
ndf =ndf.reset_index()
ndf

   index r_series  c0  c1  c2  c3  c4
0      0       r0   1   4   7  10  13
1      1       r1   2   5   8  11  14
2      2       r2   3   6   9  12  15

In [26]:
ndf.drop(['index'], axis=1)

  r_series  c0  c1  c2  c3  c4
0       r0   1   4   7  10  13
1       r1   2   5   8  11  14
2       r2   3   6   9  12  15

In [28]:
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

# 인덱스를 [r0, r1, r2, r3, r4]로 재지정
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
print(ndf)

# reindex로 발생한 NaN 값을 숫자 0으로 채우기
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index, fill_value=0)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [ ]:
# 정수형 위치 인덱스로 초기화
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf2 = df.reset_index(names=['r_series'])
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  r_series  c0  c1  c2  c3  c4
0       r0   1   4   7  10  13
1       r1   2   5   8  11  14
2       r2   3   6   9  12  15

In [34]:
# 행 인덱스를 초기화하고, 기존 인덱스를 삭제
print(df)
ndf3 = df.reset_index(drop=True)
print(ndf3)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [37]:
# 정수형 위치 인덱스로 초기화
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

# 내림차순으로 행 인덱스 정렬
ndf = df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

In [38]:
ndf2 = df.sort_index(ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [ ]:
# 정수형 위치 인덱스로 초기화
import pandas as pd

# 딕셔너리를 데이터프레임으로 변환
dict_data = {'c0': [1, 2, 3], 'c1':[4, 5, 6], 'c2': [7, 8, 9], 'c3': [10, 11, 12], 'c4': [13, 14, 15]}

# 인덱스를 {r0, r1, r2}로 지정
df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

# c1열을 기준으로 내림차순으로 정렬
ndf = df.sort_values(by='c1', ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15
    c0  c1  c2  c3  c4
r1   3   6   9  12  15
r2   2   5   8  11  14
r0   1   4   7  10  13

In [40]:
ndf2 = df.sort_values(by='c2', ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

In [41]:
ndf3 = df.sort_values(by=['c3', 'c4'], ascending=[False, True])
print(ndf3)

    c0  c1  c2  c3  c4
r1   3   6   9  12  15
r2   2   5   8  11  14
r0   1   4   7  10  13

In [43]:
# 정수형 위치 인덱스로 초기화
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': 100, '영어': 80, '수학': 90})
print(student1)

# 학생의 과목별 점수를 200으로 나누기
percentage = student1/ 200

print(percentage)
print(type(percentage))

국어    100
영어     80
수학     90
dtype: int64
국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [44]:
import pandas as pd

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': 100, '영어': 80, '수학': 90})
student2 = pd.Series({'수학': 80, '국어': 90, '영어': 80})

print(student1)
print()
print(student2)

# 두학생의 과목별 점수로 사칙연산 수행
addition = student1 + student2
print(type(addition))

print(addition)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64
<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [45]:
subtraction = student1 - student2
print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [46]:
multiplication = student1 * student2
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [47]:
division = student1 / student2
print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [48]:
# 사칙연산 결과를 데이터 프레임으로 합치기(시리즈 -> 데이터프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [51]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np

# 딕셔너리 데이터로 판다스 시리즈 만들기
student1 = pd.Series({'국어': np.nan, '영어': 80, '수학': 90})
student2 = pd.Series({'수학': 80, '국어': 90})

print(student1)
print(student2)

addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2
print(type(division))
print()

# 사칙연산 결과를 데이터프레임으로 합치기(시리즈 -> 데이터 프레임)
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
<class 'pandas.Series'>

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [ ]:
import pandas as pd
import seaborn as sns

# titanic  데이터셋에서 age, fare 2개 열을 선택하여 데이터 프레임 만들기
titanic = sns.load_dataset('titanic')
print(titanic)
df = titanic.loc[:, ['age', 'fare']]
print(df.head())
print()
print(type(df))

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]
    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

<class 'pandas.DataFrame'>

In [56]:
# 데이터프레임에 숫자 10 더하기
addition = df + 10
print(addition.head())
print()
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

<class 'pandas.DataFrame'>

In [57]:
# 데이터프레임까지 연산하기(addition -df)
subtraction = addition - df
print(subtraction.tail())
print()
print(type(subtraction))

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

<class 'pandas.DataFrame'>