# HTML 파일 불러오기
- read_html() 함수는 HTML 웹페이지에 있는 태그를 표 형식의 데이터로 모두 찾아서 데이터프레임으로 반환
- 표가 아닌 다른 HTML 요소는 Dataframe 으로 반환하지 못함

In [2]:
import pandas as pd

tables = pd.read_html('../data/sample.html')
print(tables)

[   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9,          name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True]

In [ ]:
# 표(table)의 개수 확인
print(len(tables))

2

In [4]:
tables[0]

   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9

In [5]:
tables[1]

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [6]:
# tables 리스트의 원소를 반복하면서 각각 출력
for i in range(len(tables)):
    print(tables[i])
    print('\n')

   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9


         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [7]:
df = tables[1]
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [8]:
# 'name' 열을 인덱스로 지정해서 출력
df = df.set_index(['name'])
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

In [9]:
tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds")
print(tables)

HTTPError: HTTP Error 403: Forbidden

In [12]:
url= 'https://en.wikipedia.org/wiki/Korea'

import requests 
from io import StringIO # 메모리에 있는 문자열을 파일처럼 사용할 수 있게 함

headers = {
    'User-Agent': 'Mozilla/5.0'
}

response = requests.get(url, headers = headers)
##############################################
# HTML 문자열을 StringIO 객체로 변환
# StringIO는 메모리에 있는 문자열을 파일처럼 읽을 수 있게 만들어주는 객체
tables = pd.read_html(StringIO(response.text))

print(len(tables))

28

In [13]:
tables[0]

,0,1
0,Korea shown in dark green,Korea shown in dark green
1,Geography,Geography
2,Major islands,Jeju Island
3,Area,"223,915 km2 (86,454 sq mi)"
4,Administration,Administration
5,North Korea,North Korea
6,Capital city,Pyongyang
7,Supreme Leader of North Korea,Kim Jong Un[a]
8,South Korea,South Korea
9,Capital city,Seoul
10,President of South Korea,Lee Jae Myung
11,Demographics,Demographics
12,Demonym,Korean
13,Population,"77,620,000 (2025)"
14,Pop. density,346.65/km2 (897.82/sq mi)
15,Languages,Korean
16,Additional information,Additional information
17,Time zone,Korea Standard Time and Pyongyang Time (UTC+09)
18,NaN,NaN
19,NaN,NaN
20,South Korean name,South Korean name
21,Hangul,한국
22,Hanja,韓國
23,RR,Hanguk
24,MR,Han'guk
25,North Korean name,North Korean name
26,Hangul,조선
27,Hanja,朝鮮
28,RR,Joseon
29,MR,Chosŏn

In [14]:
for i in range(len(tables)):
    print(tables[i])
    print('\n')

                                0  \
0       Korea shown in dark green
1                       Geography
2                   Major islands
3                            Area
4                  Administration
5                     North Korea
6                    Capital city
7   Supreme Leader of North Korea
8                     South Korea
9                    Capital city
10       President of South Korea
11                   Demographics
12                        Demonym
13                     Population
14                   Pop. density
15                      Languages
16         Additional information
17                      Time zone
18                            NaN
19                            NaN
20              South Korean name
21                         Hangul
22                          Hanja
23                             RR
24                             MR
25              North Korean name
26                         Hangul
27                          Hanja
28                             RR
29                             MR

                                                  1
0                         Korea shown in dark green
1                                         Geography
2                                       Jeju Island
3                        223,915 km2 (86,454 sq mi)
4                                    Administration
5                                       North Korea
6                                         Pyongyang
7                                    Kim Jong Un[a]
8                                       South Korea
9                                             Seoul
10                                    Lee Jae Myung
11                                     Demographics
12                                           Korean
13                                77,620,000 (2025)
14                        346.65/km2 (897.82/sq mi)
15                                           Korean
16                           Additional information
17  Korea Standard Time and Pyongyang Time (UTC+09)
18                                              NaN
19                                              NaN
20                                South Korean name
21                                               한국
22                                               韓國
23                                           Hanguk
24                                          Han'guk
25                                North Korean name
26                                               조선
27                                               朝鮮
28                                           Joseon
29                                           Chosŏn


                              Part of a series on the  Unnamed: 1_level_0
                                     History of Korea  Unnamed: 1_level_1
0                                                 NaN                 NaN
1   Prehistoric period Palaeolithic 700,000–8000 B...                 NaN
2                                        Palaeolithic     700,000–8000 BC
3                                           Neolithic        8000–1500 BC
4                                           * Jeulmun                 NaN
5                                          Bronze Age         1500–300 BC
6                                             * Mumun                 NaN
7                                   * Liaoning dagger                 NaN
8   Ancient period Gojoseon 2333–108 BC* Tan'gun* ...                 NaN
9                                            Gojoseon         2333–108 BC
10                                          * Tan'gun                 NaN
11                                             * Kija                 NaN
12                                            * Wiman                 NaN
13                                                Jin  4th–2nd century BC
14                                             Yemaek                 NaN
15  Proto–Three Kingdoms period Takri Dongye Buyeo...                 NaN
16  Three Kingdoms period Goguryeo 37 BC – 668 AD ...                 NaN
17                                           Goguryeo      37 BC – 668 AD
18                                            Paekche      18 BC – 660 AD
19                                              Silla      57 BC – 935 AD
20                                   Kaya confederacy              42–562
21                       Tamna (Tributary of Paekche)             498–660
22                                               Usan             512–930
23  Northern and Southern period United Silla (Uni...                 NaN
24                       United Silla (Unified Silla)             668–892
25                                             Parhae             698–926
26                                    Little Goguryeo             699–820
27                         Tamna (Tributary of Silla)             662–925
28  Later Three Kingdoms period Later Paekche 892–...                 NaN
29                                      Later Paekche             892–936
30                           Taebong (Later Goguryeo)             901–918
31                        Unified Silla (Later Silla)             892–935
32                                       Later Sabeol             919–927
33                                    Dongdan Kingdom             926–936
34                                       Later Parhae             927–935
35                                            Jeongan             938–986
36  Dynastic period Goryeo 918–1392 Tamna (Vassal ...                 NaN
37                                             Goryeo            918–1392
38                           Tamna (Vassal of Goryeo)            938–1105
39                                            Heungyo           1029–1030
40                                        Mongol rule           1270–1356
41                                             Joseon           1392–1897
42                                      Korean Empire           1897–1910
43  Colonial period Japanese occupation 1910–1945 ...                 NaN
44                                Japanese occupation           1910–1945
45                             Provisional Government           1919–1948
46  Modern period Military governments 1945–1948 N...                 NaN
47                               Military governments           1945–1948
48                               North-South division        1945–present
49                                            * North        1948–present
50                                            * South        1948–present
51  By topic Architecture Art Cuisine Currency Edu...                 NaN
52                                           Timeline                 NaN
53              North Korea portal South Korea portal                 NaN
54                                                vte                 NaN


                   0                1
0       Palaeolithic  700,000–8000 BC
1          Neolithic     8000–1500 BC
2          * Jeulmun              NaN
3         Bronze Age      1500–300 BC
4            * Mumun              NaN
5  * Liaoning dagger              NaN


           0                   1
0   Gojoseon         2333–108 BC
1  * Tan'gun                 NaN
2     * Kija                 NaN
3    * Wiman                 NaN
4        Jin  4th–2nd century BC
5     Yemaek                 NaN


                              0               1
0                      Goguryeo  37 BC – 668 AD
1                       Paekche  18 BC – 660 AD
2                         Silla  57 BC – 935 AD
3              Kaya confederacy          42–562
4  Tamna (Tributary of Paekche)         498–660
5                          Usan         512–930


                              0        1
0  United Silla (Unified Silla)  668–892
1                        Parhae  698–926
2               Little Goguryeo  699–820
3    Tamna (Tributary of Silla)  662–925


                             0        1
0                Later Paekche  892–936
1     Taebong (Later Goguryeo)  901–918
2  Unified Silla (Later Silla)  892–935
3                 Later Sabeol  919–927
4              Dongdan Kingdom  926–936
5                 Later Parhae  927–935
6                      Jeongan  938–986


                          0          1
0                    Goryeo   918–1392
1  Tamna (Vassal of Goryeo)   938–1105
2                   Heungyo  1029–1030
3               Mongol rule  1270–1356
4                    Joseon  1392–1897
5             Korean Empire  1897–1910


                        0          1
0     Japanese occupation  1910–1945
1  Provisional Government  1919–1948


                      0             1
0  Military governments     1945–1948
1  North-South division  1945–present
2               * North  1948–present
3               * South  1948–present


    0                                                  1
0 NaN  This section does not cite any sources. Please...


    0                                                  1
0 NaN  This section may contain excessive or inapprop...


  Largest cities or towns in Korea Sources: 2008 North Korean census and 2015 South Korean census  \
                                                                                             Rank
0                                                  1
1                                                  2
2                                                  3
3                                                  4
4                                                  5
5                                                  6
6                                                  7
7                                                  8
8                                                  9
9                                                 10

                                                                             \
        Name          Province     Pop. Rank.1    Name.1         Province.1
0      Seoul             Seoul  9904312     11    Goyang           Gyeonggi
1      Busan             Busan  3448737     12    Yongin           Gyeonggi
2  Pyongyang         Pyongyang  3255288     13  Seongnam           Gyeonggi
3    Incheon           Incheon  2890451     14   Bucheon           Gyeonggi
4      Daegu             Daegu  2446052     15  Cheongju  North Chungcheong
5    Daejeon           Daejeon  1538394     16   Hamhung     South Hamgyong
6    Gwangju           Gwangju  1502881     17     Ansan           Gyeonggi
7      Suwon          Gyeonggi  1194313     18  Chongjin     North Hamgyong
8      Ulsan             Ulsan  1166615     19    Jeonju       North Jeolla
9   Changwon  South Gyeongsang  1059241     20   Cheonan  South Chungcheong


   Pop..1 Unnamed: 8_level_1 Unnamed: 9_level_1
0  990073                NaN                NaN
1  971327                NaN                NaN
2  948757                NaN                NaN
3  843794                NaN                NaN
4  833276                NaN                NaN
5  768551                NaN                NaN
6  747035                NaN                NaN
7  667929                NaN                NaN
8  658172                NaN                NaN
9  629062                NaN                NaN


    0                                                  1
0 NaN  This section does not cite any sources. Please...


                   vteIndex of Korea-related articles  \
0                             North Korea South Korea
1   History of KoreaGeneral Military history Monar...
2                                    History of Korea
3   General Military history Monarchs Timeline Chr...
4                                             General
5                                          Chronology
6   Geography of KoreaGeneral Borders Korean Penin...
7                                  Geography of Korea
8   General Borders Korean Peninsula Islands Lakes...
9                                             General
10                           Geography of North Korea
11                           Geography of South Korea
12  PoliticsNorth Korea Overview Constitution Fore...
13                                           Politics
14  North Korea Overview Constitution Foreign rela...
15                                        North Korea
16                                        South Korea
17  EconomyNorth Korea Overview Agriculture Automo...
18                                            Economy
19  North Korea Overview Agriculture Automotive in...
20                                        North Korea
21                                        South Korea
22  Demographics Koreans Demographics of North Kor...
23                                       Demographics
24  Koreans Demographics of North Korea Demographi...
25  Culture of KoreaGeneral Cinema North South 100...
26                                   Culture of Korea
27  General Cinema North South 100 Cultural Symbol...
28                                            General
29                                         Korean art
30                             Culture of North Korea
31                             Culture of South Korea

                 vteIndex of Korea-related articles.1
0                             North Korea South Korea
1   History of KoreaGeneral Military history Monar...
2                                    History of Korea
3   General Military history Monarchs Timeline Chr...
4                  Military history Monarchs Timeline
5   Gojoseon Dangun Joseon / Gija Joseon / Wiman J...
6   Geography of KoreaGeneral Borders Korean Penin...
7                                  Geography of Korea
8   General Borders Korean Peninsula Islands Lakes...
9   Borders Korean Peninsula Islands Lakes Mountai...
10  Administrative divisions Cities Special cities...
11  Administrative divisions Environment Cities Sp...
12  PoliticsNorth Korea Overview Constitution Fore...
13                                           Politics
14  North Korea Overview Constitution Foreign rela...
15  Overview Constitution Foreign relations Relati...
16  Overview Constitution Foreign relations Relati...
17  EconomyNorth Korea Overview Agriculture Automo...
18                                            Economy
19  North Korea Overview Agriculture Automotive in...
20  Overview Agriculture Automotive industry Energ...
21  Overview Agriculture Automotive industry Chaeb...
22  Demographics Koreans Demographics of North Kor...
23                                       Demographics
24  Koreans Demographics of North Korea Demographi...
25  Culture of KoreaGeneral Cinema North South 100...
26                                   Culture of Korea
27  General Cinema North South 100 Cultural Symbol...
28  Cinema North South 100 Cultural Symbols Cuisin...
29  Architecture Calligraphy Drama Literature Trad...
30  Education Literature Religion Smoking Sport Ar...
31  Education Literature Religion Smoking Sport Cu...


                                    History of Korea  \
0  General Military history Monarchs Timeline Chr...
1                                            General
2                                         Chronology

                                  History of Korea.1
0  General Military history Monarchs Timeline Chr...
1                 Military history Monarchs Timeline
2  Gojoseon Dangun Joseon / Gija Joseon / Wiman J...


            0                                                  1
0     General                 Military history Monarchs Timeline
1  Chronology  Gojoseon Dangun Joseon / Gija Joseon / Wiman J...


                                  Geography of Korea  \
0  General Borders Korean Peninsula Islands Lakes...
1                                            General
2                           Geography of North Korea
3                           Geography of South Korea

                                Geography of Korea.1
0  General Borders Korean Peninsula Islands Lakes...
1  Borders Korean Peninsula Islands Lakes Mountai...
2  Administrative divisions Cities Special cities...
3  Administrative divisions Environment Cities Sp...


                          0                                                  1
0                   General  Borders Korean Peninsula Islands Lakes Mountai...
1  Geography of North Korea  Administrative divisions Cities Special cities...
2  Geography of South Korea  Administrative divisions Environment Cities Sp...


                                            Politics  \
0  North Korea Overview Constitution Foreign rela...
1                                        North Korea
2                                        South Korea

                                          Politics.1
0  North Korea Overview Constitution Foreign rela...
1  Overview Constitution Foreign relations Relati...
2  Overview Constitution Foreign relations Relati...


             0                                                  1
0  North Korea  Overview Constitution Foreign relations Relati...
1  South Korea  Overview Constitution Foreign relations Relati...


                                             Economy  \
0  North Korea Overview Agriculture Automotive in...
1                                        North Korea
2                                        South Korea

                                           Economy.1
0  North Korea Overview Agriculture Automotive in...
1  Overview Agriculture Automotive industry Energ...
2  Overview Agriculture Automotive industry Chaeb...


             0                                                  1
0  North Korea  Overview Agriculture Automotive industry Energ...
1  South Korea  Overview Agriculture Automotive industry Chaeb...


                                        Demographics  \
0  Koreans Demographics of North Korea Demographi...

                                      Demographics.1
0  Koreans Demographics of North Korea Demographi...


                                    Culture of Korea  \
0  General Cinema North South 100 Cultural Symbol...
1                                            General
2                                         Korean art
3                             Culture of North Korea
4                             Culture of South Korea

                                  Culture of Korea.1
0  General Cinema North South 100 Cultural Symbol...
1  Cinema North South 100 Cultural Symbols Cuisin...
2  Architecture Calligraphy Drama Literature Trad...
3  Education Literature Religion Smoking Sport Ar...
4  Education Literature Religion Smoking Sport Cu...


                        0                                                  1
0                 General  Cinema North South 100 Cultural Symbols Cuisin...
1              Korean art  Architecture Calligraphy Drama Literature Trad...
2  Culture of North Korea  Education Literature Religion Smoking Sport Ar...
3  Culture of South Korea  Education Literature Religion Smoking Sport Cu...


             vteEast Asia                                     vteEast Asia.1  \
0   Countries and regions  China Hong Kong Macau Mainland Japan Ryukyu Ko...
1           Ethnic groups  Ainu Han Chinese subgroups Hui Japanese Yamato...
2                 Culture  Age reckoning Architecture‎ Art Chinese Japane...
3             Environment  East Asia Climate Partnership Monsoon Rainy se...
4    Economy and Politics  China–Japan–South Korea trilateral summit Comp...
5                 History  Archaeology Archaeological cultures Bronze Age...
6                  Sports  China–Japan–Korea Friendship Athletic Meeting ...
7               Education  Association of East Asian Research Universitie...
8                Military  Horses in East Asian warfare Bansenshūkai Miya...
9  Science and technology  Needham Research Institute Printing Swords Tra...

   vteEast Asia.2
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN

