# JSON 파일 불러오기
- 자바스크립트에서 유래한 데이터 공유를 목적으로 개발된 특수 파일 형식
- 파이썬 딕셔너리 형태와 유사하게 'key:value' 구조를 가짐
- read_json() 함수를 사용해서 JSON 파일이 데이터프레임으로 변환

In [ ]:
import pandas as pd

df = pd.read_json('../data/read_json_sample.json')
df

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [3]:
# 인덱스 출력
df.index

Index(['pandas', 'NumPy', 'matplotlib'], dtype='object')

In [ ]:
# orient 속성: 'index'
# JSON 객체의 키를 행으로 변환하는데 사용
df2 = pd.read_json('../data/read_json_sample.json', orient = 'index')
df2

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

In [5]:
# orient 속성: 'columns'
# JSON 객체의 키를 열로 변환하는데 사용
df3 = pd.read_json('../data/read_json_sample.json', orient = 'columns')
df3

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [6]:
# transpose()는 행과 열의 위치를 서로 바꾸는 메소드
print(df3.transpose())

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True