# 판다스 실습_260708
## 김찬영

In [112]:
import pandas as pd
import numpy as np
import seaborn as sns

### Ex 1-21

In [113]:
##Ex 1-21
# # 딕셔너리를 데이터로 판다스 만들기
# student1 = pd.Series({'국어':100, '영어':80, '수학':90})
# print(student1)

In [114]:
# # 학생의 과목별 점수를 200으로 나누기
# percentage = student1/200

In [115]:
# print(percentage)
# print(type(percentage))

### Ex 1-22

In [116]:
# # 딕셔너리를 데이터로 판다스 만들기
# student1 = pd.Series({'국어':100, '영어':80, '수학':90})
# student2 = pd.Series({'수학':80, '국어':90, '영어':80})

In [117]:
# print(student1)
# print('\n')
# print(student2)

In [118]:
# # 두 학생의 과목별 점수로 사칙연산 수행
# addition = student1 + student2
# print(type(addition))
# print(addition)

In [119]:
# substraction = student1 - student2
# print(type(substraction))
# print(substraction)

In [120]:
# multiplication = student1 * student2
# print(type(multiplication))
# print(multiplication)

In [121]:
# division = student1 / student2
# print(type(division))
# print(division)

In [122]:
# # 사칙연산 결과를 데이터프레임으로 합치기(시리즈 -> 데이터프레임)
# result = pd.DataFrame([addition, substraction, multiplication, division],
#                       index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
# print(result)

### Ex 1-23

In [123]:
# # 딕셔너리 데이터로 판다스 시리즈 만들기
# student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
# student2 = pd.Series({'수학':80, '국어':90})

In [124]:
# print(student1)
# print(student2)

In [125]:
# # 두 학생의 과목별 점수로 사칙연산 수행(시리즈 vs 시리즈)
# addition = student1 + student2 #덧셈
# substraction = student1 - student2 #뺄셈
# multiplication = student1 * student2 #곱셈
# division = student1 / student2 #나눗셈
# print(type(division))
# print('\n')

In [126]:
# # 사칙연산 결과를 데이터프레임으로 합치기(시리즈 -> 데이터프레임)
# result = pd.DataFrame([addition, substraction, multiplication, division],
#                       index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
# print(result)

### Ex 1-24

In [127]:
# # 딕셔너리 데이터로 판다스 시리즈 만들기
# student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
# student2 = pd.Series({'수학':80, '국어':90})

In [128]:
# print(student1)
# print(student2)

In [129]:
# # 두 학생의 과목별 점수로 사칙연산 수행(연산 메소드 사용)
# sr_add = student1.add(student2, fill_value=0)
# sr_sub = student1.sub(student2, fill_value=0)
# sr_mul = student1.mul(student2, fill_value=0)
# sr_div = student1.div(student2, fill_value=0)

In [130]:
# # 사칙 연산 결과를 데이터프레임으로 합치기(시리즈 -> 데이터프레임)
# result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
#           index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])
# print(result)

### Ex 1-25

In [131]:
# # titanic 데이터 셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
# titanic = sns.load_dataset('titanic')
# df = titanic.loc[:, ['age', 'fare']]
# print(df.head())
# print('\n')
# print(type(df))

In [132]:
# #데이터프레임에 숫자 10 더하기
# addition = df + 10
# print(addition.head())
# print('\n')
# print(type(addition))

### Ex 1-26

In [133]:
# # titanic 데이터 셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
# titanic = sns.load_dataset('titanic')
# df = titanic.loc[:, ['age', 'fare']]
# print(df.tail())
# print('\n')
# print(type(df))

In [134]:
# #데이터프레임에 숫자 10 더하기
# addition = df + 10
# print(addition.tail())
# print('\n')
# print(type(addition))
# print('\n')

In [135]:
# #데이터프레임끼리 연산하기(addition - df)
# substraction = addition - df
# print(substraction.tail())
# print('\n')
# print(type(substraction))

In [136]:
# # 사칙연산 수행(연산 메소드 사용)
# sample1 = addition.tail()
# sample2 = substraction.tail().fillna(0.0)
#
# print(sample1)
# print(sample2)

In [137]:
# df.add = sample1.add(sample2, fill_value=0) #덧셈
# df.sub = sample1.sub(sample2, fill_value=0) #뺄셈
# df.mul = sample1.mul(sample2, fill_value=0) #곱셈
# df.div = sample1.div(sample2, fill_value=0) #나눗셈

In [138]:
# print(df.add)
# print(df.sub)
# print(df.mul)
# print(df.div)

### Ex 1-27

In [139]:
# titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic')

# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임을 만들기
df = titanic.loc[0:9, ['age', 'fare']]

# 데이터프레임 출력
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [140]:
# 조건식 적용(20세 미만: age < 20)
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [141]:
# 불린 인덱싱(20세 미만의 조건을 충족하는 행을 필터링)
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [142]:
# 불린 인덱싱(loc 인덱서 활용)
df.loc[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [143]:
# 불린 인덱싱(NOT 논리연산)
df.loc[~(df['age'] < 20)]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [145]:
# 나이가 10대(10~19세)인 승객(AND 논리연산)
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [146]:
# 나이가 10대 미만(0~9세)인 승객(AND 논리연산,loc인덴서)
mask2 = (titanic.age < 10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [147]:
# 나이가 10세 미만(0~9세) 또는 60세 이상인 승객(OR 논리연산)
# age, sex, alone 열만 선택 (loc 인덱서, fancy indexing)
mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [148]:
# 불린 시리즈를 새로운 열로 추가
df['age_under_20'] = (df['age'] < 20)
df.head()

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False